# ======================================================
# KITTY + PYWAL
# ======================================================

include ~/.cache/wal/colors-kitty.conf

# ======================================================
# SHELL
# ======================================================

shell /bin/zsh
shell_integration enabled

term xterm-kitty

editor nvim

# ======================================================
# FONT
# ======================================================

font_family FiraCode Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto

font_size 13.0

disable_ligatures never

# ======================================================
# WINDOW
# ======================================================

window_padding_width 12

background_opacity 0.72
dynamic_background_opacity yes

remember_window_size yes

initial_window_width 1000
initial_window_height 650

confirm_os_window_close 0

# ======================================================
# CURSOR
# ======================================================

cursor_shape block
cursor_blink_interval 0.5

# ======================================================
# SCROLLBACK
# ======================================================

scrollback_lines 10000

wheel_scroll_multiplier 5.0

# ======================================================
# TABS
# ======================================================

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

active_tab_font_style bold

# ======================================================
# PERFORMANCE
# ======================================================

enable_audio_bell no
visual_bell_duration 0.1

repaint_delay 10
input_delay 3
sync_to_monitor yes

# ======================================================
# CLIPBOARD
# ======================================================

copy_on_select yes

clipboard_control write-clipboard write-primary

# ======================================================
# REMOTE CONTROL
# ======================================================

allow_remote_control yes
listen_on unix:/tmp/kitty

# ======================================================
# KEYBINDS
# ======================================================

map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+w close_tab

map ctrl+shift+enter new_window_with_cwd

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+shift+equal increase_font_size
map ctrl+shift+minus decrease_font_size

map ctrl+shift+backspace restore_font_size

# ======================================================
# LAYOUTS
# ======================================================

enabled_layouts tall,fat,grid,stack,splits

# ======================================================
# URLS
# ======================================================

detect_urls yes
open_url_with default