# Basic colors
foreground              #f1dedc
background              #1a1110
selection_foreground    #ffdad5
selection_background    #5d3f3b

# Cursor colors
cursor                  #ffb4a9
cursor_text_color       #561e17

# URL underline color when hovering with mouse
url_color               #dec38c

# Kitty window border colors
active_border_color     #ffb4a9
inactive_border_color   #534341
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #ffdad5
active_tab_background   #73342b
inactive_tab_foreground #d8c2be
inactive_tab_background #271d1c
tab_bar_background      #1a1110

# Colors for marks
mark1_foreground #561e17
mark1_background #ffb4a9
mark2_foreground #442926
mark2_background #e7bdb7
mark3_foreground #3e2e04
mark3_background #dec38c

# The 16 terminal colors
# black
color0 #534341
color8 #a08c89

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #ffb4a9
color10 #ffdad5

# yellow
color3  #dec38c
color11 #fcdfa6

# blue
color4  #e7bdb7
color12 #ffdad5

# magenta
color5  #73342b
color13 #904a41

# cyan
color6  #5d3f3b
color14 #574419

# white
color7  #d8c2be
color15 #f1dedc
