# Basic colors
foreground              #e2e3d8
background              #12140e
selection_foreground    #dbe7c8
selection_background    #404a33

# Cursor colors
cursor                  #b1d18a
cursor_text_color       #1e3702

# URL underline color when hovering with mouse
url_color               #a0cfcc

# Kitty window border colors
active_border_color     #b1d18a
inactive_border_color   #44483d
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #cceda4
active_tab_background   #344e16
inactive_tab_foreground #c5c8ba
inactive_tab_background #1e201a
tab_bar_background      #12140e

# Colors for marks
mark1_foreground #1e3702
mark1_background #b1d18a
mark2_foreground #2a331e
mark2_background #bfcbad
mark3_foreground #003735
mark3_background #a0cfcc

# The 16 terminal colors
# black
color0 #44483d
color8 #8e9285

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #b1d18a
color10 #cceda4

# yellow
color3  #a0cfcc
color11 #bbece8

# blue
color4  #bfcbad
color12 #dbe7c8

# magenta
color5  #344e16
color13 #4b662c

# cyan
color6  #404a33
color14 #1f4e4b

# white
color7  #c5c8ba
color15 #e2e3d8
