#################
### AUTOSTART ###
#################

$terminal    = kitty
$fileManager = dolphin
$menu        = rofi -show drun
#################
### AUTOSTART ###
#################

exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS
exec-once = waybar
exec-once = swaync
exec-once = awww-daemon
exec-once = ~/.config/hypr/scripts/wallpaper.sh current