##############################
### WINDOWS AND WORKSPACES ###
##############################

# Suppress maximize requests from all apps
windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

# Fix XWayland dragging issues
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# hyprland-run float position
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# Obsidian transparency
windowrule {
name = obsidian-opacity
    match:class = obsidian
opacity = 0.7 0.7
}

# VS Code transparency
windowrule {
name = vscode-opacity
    match:class = code-oss
opacity = 0.7 0.7
}
